; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.12 on Fri Jun 20 2025 22:59:08 GMT-0400 (Eastern Daylight Time)

M116 P1 ; wait for tool temperatures to be reached
